/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookDTO } from './BookDTO';
import {
    BookDTOFromJSON,
    BookDTOFromJSONTyped,
    BookDTOToJSON,
} from './BookDTO';

/**
 * 
 * @export
 * @interface AuthorDTO
 */
export interface AuthorDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    nationality?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    biography?: string | null;
    /**
     * 
     * @type {Array<BookDTO>}
     * @memberof AuthorDTO
     */
    books?: Array<BookDTO> | null;
}

/**
 * Check if a given object implements the AuthorDTO interface.
 */
export function instanceOfAuthorDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthorDTOFromJSON(json: any): AuthorDTO {
    return AuthorDTOFromJSONTyped(json, false);
}

export function AuthorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'nationality': !exists(json, 'nationality') ? undefined : json['nationality'],
        'biography': !exists(json, 'biography') ? undefined : json['biography'],
        'books': !exists(json, 'books') ? undefined : (json['books'] === null ? null : (json['books'] as Array<any>).map(BookDTOFromJSON)),
    };
}

export function AuthorDTOToJSON(value?: AuthorDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'nationality': value.nationality,
        'biography': value.biography,
        'books': value.books === undefined ? undefined : (value.books === null ? null : (value.books as Array<any>).map(BookDTOToJSON)),
    };
}

