/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookUpdateDTO
 */
export interface BookUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof BookUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BookUpdateDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookUpdateDTO
     */
    author?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BookUpdateDTO
     */
    pages?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BookUpdateDTO
     */
    genre?: string | null;
}

/**
 * Check if a given object implements the BookUpdateDTO interface.
 */
export function instanceOfBookUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookUpdateDTOFromJSON(json: any): BookUpdateDTO {
    return BookUpdateDTOFromJSONTyped(json, false);
}

export function BookUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'author': !exists(json, 'author') ? undefined : json['author'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'pages': !exists(json, 'pages') ? undefined : json['pages'],
        'genre': !exists(json, 'genre') ? undefined : json['genre'],
    };
}

export function BookUpdateDTOToJSON(value?: BookUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'author': value.author,
        'description': value.description,
        'pages': value.pages,
        'genre': value.genre,
    };
}

