/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackAddDTO
 */
export interface FeedbackAddDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    q1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    q2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    q3?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    q4?: string | null;
}

/**
 * Check if a given object implements the FeedbackAddDTO interface.
 */
export function instanceOfFeedbackAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackAddDTOFromJSON(json: any): FeedbackAddDTO {
    return FeedbackAddDTOFromJSONTyped(json, false);
}

export function FeedbackAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'q1': !exists(json, 'q1') ? undefined : json['q1'],
        'q2': !exists(json, 'q2') ? undefined : json['q2'],
        'q3': !exists(json, 'q3') ? undefined : json['q3'],
        'q4': !exists(json, 'q4') ? undefined : json['q4'],
    };
}

export function FeedbackAddDTOToJSON(value?: FeedbackAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'q1': value.q1,
        'q2': value.q2,
        'q3': value.q3,
        'q4': value.q4,
    };
}

