/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { GenreDTOPagedResponse } from './GenreDTOPagedResponse';
import {
    GenreDTOPagedResponseFromJSON,
    GenreDTOPagedResponseFromJSONTyped,
    GenreDTOPagedResponseToJSON,
} from './GenreDTOPagedResponse';

/**
 * 
 * @export
 * @interface GenreDTOPagedResponseRequestResponse
 */
export interface GenreDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {GenreDTOPagedResponse}
     * @memberof GenreDTOPagedResponseRequestResponse
     */
    response?: GenreDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof GenreDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the GenreDTOPagedResponseRequestResponse interface.
 */
export function instanceOfGenreDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GenreDTOPagedResponseRequestResponseFromJSON(json: any): GenreDTOPagedResponseRequestResponse {
    return GenreDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function GenreDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : GenreDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function GenreDTOPagedResponseRequestResponseToJSON(value?: GenreDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': GenreDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

