/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenreAddDTO
 */
export interface GenreAddDTO {
    /**
     * 
     * @type {string}
     * @memberof GenreAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GenreAddDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the GenreAddDTO interface.
 */
export function instanceOfGenreAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GenreAddDTOFromJSON(json: any): GenreAddDTO {
    return GenreAddDTOFromJSONTyped(json, false);
}

export function GenreAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function GenreAddDTOToJSON(value?: GenreAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}

