/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { GenreDTO } from './GenreDTO';
import {
    GenreDTOFromJSON,
    GenreDTOFromJSONTyped,
    GenreDTOToJSON,
} from './GenreDTO';

/**
 * 
 * @export
 * @interface GenreDTORequestResponse
 */
export interface GenreDTORequestResponse {
    /**
     * 
     * @type {GenreDTO}
     * @memberof GenreDTORequestResponse
     */
    response?: GenreDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof GenreDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the GenreDTORequestResponse interface.
 */
export function instanceOfGenreDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GenreDTORequestResponseFromJSON(json: any): GenreDTORequestResponse {
    return GenreDTORequestResponseFromJSONTyped(json, false);
}

export function GenreDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : GenreDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function GenreDTORequestResponseToJSON(value?: GenreDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': GenreDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

