/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GenreDTO } from './GenreDTO';
import {
    GenreDTOFromJSON,
    GenreDTOFromJSONTyped,
    GenreDTOToJSON,
} from './GenreDTO';

/**
 * 
 * @export
 * @interface GenreDTOPagedResponse
 */
export interface GenreDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof GenreDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GenreDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof GenreDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<GenreDTO>}
     * @memberof GenreDTOPagedResponse
     */
    data?: Array<GenreDTO> | null;
}

/**
 * Check if a given object implements the GenreDTOPagedResponse interface.
 */
export function instanceOfGenreDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GenreDTOPagedResponseFromJSON(json: any): GenreDTOPagedResponse {
    return GenreDTOPagedResponseFromJSONTyped(json, false);
}

export function GenreDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(GenreDTOFromJSON)),
    };
}

export function GenreDTOPagedResponseToJSON(value?: GenreDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(GenreDTOToJSON)),
    };
}

