/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenreUpdateDTO
 */
export interface GenreUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof GenreUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GenreUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GenreUpdateDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the GenreUpdateDTO interface.
 */
export function instanceOfGenreUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GenreUpdateDTOFromJSON(json: any): GenreUpdateDTO {
    return GenreUpdateDTOFromJSONTyped(json, false);
}

export function GenreUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function GenreUpdateDTOToJSON(value?: GenreUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
    };
}

