/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { RatingDTO } from './RatingDTO';
import {
    RatingDTOFromJSON,
    RatingDTOFromJSONTyped,
    RatingDTOToJSON,
} from './RatingDTO';

/**
 * 
 * @export
 * @interface RatingDTORequestResponse
 */
export interface RatingDTORequestResponse {
    /**
     * 
     * @type {RatingDTO}
     * @memberof RatingDTORequestResponse
     */
    response?: RatingDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RatingDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the RatingDTORequestResponse interface.
 */
export function instanceOfRatingDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RatingDTORequestResponseFromJSON(json: any): RatingDTORequestResponse {
    return RatingDTORequestResponseFromJSONTyped(json, false);
}

export function RatingDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : RatingDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RatingDTORequestResponseToJSON(value?: RatingDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': RatingDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

