/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Book } from './Book';
import {
    BookFromJSON,
    BookFromJSONTyped,
    BookToJSON,
} from './Book';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Rating
 */
export interface Rating {
    /**
     * 
     * @type {string}
     * @memberof Rating
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Rating
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Rating
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Rating
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof Rating
     */
    bookId?: string | null;
    /**
     * 
     * @type {Book}
     * @memberof Rating
     */
    book?: Book;
    /**
     * 
     * @type {string}
     * @memberof Rating
     */
    userId?: string | null;
    /**
     * 
     * @type {User}
     * @memberof Rating
     */
    user?: User;
}

/**
 * Check if a given object implements the Rating interface.
 */
export function instanceOfRating(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RatingFromJSON(json: any): Rating {
    return RatingFromJSONTyped(json, false);
}

export function RatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rating {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'value': !exists(json, 'value') ? undefined : json['value'],
        'bookId': !exists(json, 'bookId') ? undefined : json['bookId'],
        'book': !exists(json, 'book') ? undefined : BookFromJSON(json['book']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function RatingToJSON(value?: Rating | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'value': value.value,
        'bookId': value.bookId,
        'book': BookToJSON(value.book),
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

