/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingUpdateDTO
 */
export interface RatingUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof RatingUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof RatingUpdateDTO
     */
    value?: number | null;
}

/**
 * Check if a given object implements the RatingUpdateDTO interface.
 */
export function instanceOfRatingUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RatingUpdateDTOFromJSON(json: any): RatingUpdateDTO {
    return RatingUpdateDTOFromJSONTyped(json, false);
}

export function RatingUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function RatingUpdateDTOToJSON(value?: RatingUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'value': value.value,
    };
}

