/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingAddDTO
 */
export interface RatingAddDTO {
    /**
     * 
     * @type {string}
     * @memberof RatingAddDTO
     */
    bookId?: string;
    /**
     * 
     * @type {number}
     * @memberof RatingAddDTO
     */
    value?: number;
}

/**
 * Check if a given object implements the RatingAddDTO interface.
 */
export function instanceOfRatingAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RatingAddDTOFromJSON(json: any): RatingAddDTO {
    return RatingAddDTOFromJSONTyped(json, false);
}

export function RatingAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookId': !exists(json, 'bookId') ? undefined : json['bookId'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function RatingAddDTOToJSON(value?: RatingAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookId': value.bookId,
        'value': value.value,
    };
}

