/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RatingEssential
 */
export interface RatingEssential {
    /**
     * 
     * @type {number}
     * @memberof RatingEssential
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof RatingEssential
     */
    userId?: string | null;
}

/**
 * Check if a given object implements the RatingEssential interface.
 */
export function instanceOfRatingEssential(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RatingEssentialFromJSON(json: any): RatingEssential {
    return RatingEssentialFromJSONTyped(json, false);
}

export function RatingEssentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatingEssential {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function RatingEssentialToJSON(value?: RatingEssential | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'userId': value.userId,
    };
}

