/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewAddDTO
 */
export interface ReviewAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ReviewAddDTO
     */
    bookId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewAddDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReviewAddDTO
     */
    content?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ReviewAddDTO
     */
    rating?: number;
}

/**
 * Check if a given object implements the ReviewAddDTO interface.
 */
export function instanceOfReviewAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReviewAddDTOFromJSON(json: any): ReviewAddDTO {
    return ReviewAddDTOFromJSONTyped(json, false);
}

export function ReviewAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookId': !exists(json, 'bookId') ? undefined : json['bookId'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
    };
}

export function ReviewAddDTOToJSON(value?: ReviewAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookId': value.bookId,
        'title': value.title,
        'content': value.content,
        'rating': value.rating,
    };
}

