/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewDTO
 */
export interface ReviewDTO {
    /**
     * 
     * @type {string}
     * @memberof ReviewDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReviewDTO
     */
    content?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ReviewDTO
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewDTO
     */
    bookId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReviewDTO
     */
    userId?: string | null;
}

/**
 * Check if a given object implements the ReviewDTO interface.
 */
export function instanceOfReviewDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReviewDTOFromJSON(json: any): ReviewDTO {
    return ReviewDTOFromJSONTyped(json, false);
}

export function ReviewDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'bookId': !exists(json, 'bookId') ? undefined : json['bookId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function ReviewDTOToJSON(value?: ReviewDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'content': value.content,
        'rating': value.rating,
        'bookId': value.bookId,
        'userId': value.userId,
    };
}

