/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewUpdateDTO
 */
export interface ReviewUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ReviewUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewUpdateDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReviewUpdateDTO
     */
    content?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ReviewUpdateDTO
     */
    rating?: number | null;
}

/**
 * Check if a given object implements the ReviewUpdateDTO interface.
 */
export function instanceOfReviewUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReviewUpdateDTOFromJSON(json: any): ReviewUpdateDTO {
    return ReviewUpdateDTOFromJSONTyped(json, false);
}

export function ReviewUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
    };
}

export function ReviewUpdateDTOToJSON(value?: ReviewUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'content': value.content,
        'rating': value.rating,
    };
}

