/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Book } from './Book';
import {
    BookFromJSON,
    BookFromJSONTyped,
    BookToJSON,
} from './Book';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Review
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Review
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    bookId?: string;
    /**
     * 
     * @type {Book}
     * @memberof Review
     */
    book?: Book;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof Review
     */
    user?: User;
}

/**
 * Check if a given object implements the Review interface.
 */
export function instanceOfReview(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'title': !exists(json, 'title') ? undefined : json['title'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'bookId': !exists(json, 'bookId') ? undefined : json['bookId'],
        'book': !exists(json, 'book') ? undefined : BookFromJSON(json['book']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function ReviewToJSON(value?: Review | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'title': value.title,
        'content': value.content,
        'bookId': value.bookId,
        'book': BookToJSON(value.book),
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

